Adding problem set 6 lessons for submission
The-Comet-Gaming/CS50_2024_Submissions pull request #19
Opened 2024-07-24 10:22 UTC by The-Comet-Gaming

2024-07-24 10:38 UTC, ChrisMellor requested changes

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 0 - sentimental-hello/hello.py
> +
Double blank lines, you only need the one

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 1 - sentimental-mario-less/mario.py
> +    k = n - j
Note that these variable names are very unclear what they are

Either add comments to explain what they are for, or rename them to something more relevant
P.S Code should be self documenting, I shouldn't have to "try to work it out" comments is the less ideal situation and should be saved for more complication code that can't be simplified right now

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 3 - sentimental-cash/cash.py
> +def CalculateCoins(coinValue):
In Python, local variables typically use the Snake Case naming convention, which is `snake_case`

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 3 - sentimental-cash/cash.py
> +    global Change
Try to avoid using global variables if possible

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 3 - sentimental-cash/cash.py
> +        Change = Change - coinValue * n
You may want to revisit this solution, there is a much cleaner way to handle this within Python

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 4 - sentimental-credit/credit.py
> +                    CardType = name
This is over engineered, please take another look at it, and try to make the solution simpler. I think you can learn a lot trying to reduce the amount of code here

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 5 - sentimental-readability/readability.py
> +# imports,
Unneeded comment?

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 5 - sentimental-readability/readability.py
> +              (0.296 * (len(Sentences) / WordCount * 100)) - 15.8)
You're duplicating Maths here. See if you can simplify it.

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 5 - sentimental-readability/readability.py
> +Words = findall("[ ]", Text)
I believe there are simpler and better native python functions to use than this. Specifically for finding all the words

2024-07-24 10:38 UTC, ChrisMellor commented on src/python/problem set 6/lesson 6 - dna/dna.py
>      # TODO: Check for command-line usage
Is this finished?

2024-07-25 05:59 UTC, The-Comet-Gaming commented on src/python/problem set 6/lesson 3 - sentimental-cash/cash.py
> +    global Change
I'll make sure to avoiding using them from now on and I'll make it so a global variable isn't required in the next version.

Would you be able to explain why it is better practice to avoid using them in Python?

2024-07-25 05:59 UTC, The-Comet-Gaming commented on src/python/problem set 6/lesson 3 - sentimental-cash/cash.py
> +        Change = Change - coinValue * n
I've had a look through the documentation for [mathematic functions](https://docs.python.org/3/library/math.html#math.trunc) and didn't see anything that I thought would be helpful / in line with what you alluded to. I don't want the answer given to me, just a hint/guidance of what to look for would be appreciated.

2024-07-25 05:59 UTC, The-Comet-Gaming commented on src/python/problem set 6/lesson 4 - sentimental-credit/credit.py
> +                    CardType = name
I will do my best to reduce it down. I just can't think of anyway to do that currently and if I keep thinking about it and coming up blank right now. I'll question if I actually have the knack for this even more than I already am.

2024-07-25 08:44 UTC, ChrisMellor commented on src/python/problem set 6/lesson 0 - sentimental-hello/hello.py
> +
As long as you're consistent, and you're following the standards of a code base (or documented guideline in this case), it's fine

2024-07-25 08:49 UTC, ChrisMellor commented on src/python/problem set 6/lesson 3 - sentimental-cash/cash.py
> +    global Change
Global variables are just bad everywhere. It comes back to the same issues of
- Able to update the value from everywhere and anywhere
- Bulks the available objects at anywhere in that namespace, making it more likely to find a naming conflict
- Much harder to restrict to show _why_ a global value needs to be changed, and when
- It's a nightmare for testing 🙃
- It makes your code more brittle and less flexible, which is something that will make a lot more sense when you learn about the SOLID principles

2024-07-25 08:52 UTC, ChrisMellor commented on src/python/problem set 6/lesson 3 - sentimental-cash/cash.py
> +        Change = Change - coinValue * n
From a code telling POV, you don't need that if statement
`if Change < coinValue:`

You can approach this so it can be much smaller

You're do a lot of the maths yourself, accounting for the floor of a calculation yourself. Is there mathematical operators that could take advantage of a "non round" number? 🤔

2024-07-26 09:53 UTC, The-Comet-Gaming commented on src/python/problem set 6/lesson 3 - sentimental-cash/cash.py
> +        Change = Change - coinValue * n
Well I think I can say that it was smaller and much easier to solve when I had the answer a google search and scroll down a webpage away.

2024-07-26 09:54 UTC, The-Comet-Gaming commented on src/python/problem set 6/lesson 4 - sentimental-credit/credit.py
> +                    CardType = name
I can at least say I've thought of another way to go about the problem. Can't say that it works in practice yet but the theory is solid. Also can't say that it isn't over engineered either.

2024-07-27 15:37 UTC, ChrisMellor requested changes

2024-07-27 15:37 UTC, ChrisMellor commented on src/python/problem set 6/lesson 4 - sentimental-credit/credit.py
> +    return multiplied_number
All this can be significantly reduced still. 

1. Remove card_type as a parameter, just return a boolean and output the print from outside this function. You're making it do multiple things
2. You have multiple branches for logic in your code here. You only need 2 if statements really

`if k % 2 == 0:` This is used twice, suggesting there is a more optimal way of handling all of this

3. `multiplier` is a nice extraction, but I think it's lead you down the wrong route. If you can reduce the if statements, you could potentially end up calling this once

2024-07-28 11:51 UTC, merged